[package]
name = "chiron"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "stream"] }
futures-util = "0.3"
tokio-util = "0.7"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
uuid = { version = "1.0", features = ["v4", "serde"] }
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dirs = "5.0"
dotenvy = "0.15"
scraper = "0.17"
html2text = "0.6"
regex = "1.0"
url = "2.4"
async-trait = "0.1"
mediawiki = "0.2"
